services:
  - type: web
    name: sosai-backend
    env: python
    runtime: python3
    rootDir: ai-service
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        value: your_openai_api_key_here
      - key: PORT
        value: 8001
    healthCheckPath: /
    autoDeploy: true

  - type: web
    name: sosai-frontend
    env: node
    rootDir: ai-service/frontend
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://sosai-backend.onrender.com
    healthCheckPath: /
    autoDeploy: true 