services:
  - type: web
    name: sosai-backend
    env: python
    runtime: python3
    pythonVersion: 3.9.12
    rootDir: ai-service
    buildCommand: |
      python -m pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn app:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: OPENAI_API_KEY
        value: your_openai_api_key_here
      - key: PORT
        value: 8001
    healthCheckPath: /
    autoDeploy: true

  - type: static
    name: sosai-frontend
    env: static
    rootDir: ai-service/frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://sosai-backend.onrender.com 